export interface FacultyProfile {
  slug: string;
  name: string;
  photo: string;
  designation: string;
  department: string;
  dob: string;
  doj: string;
  qualifications: string;
  email: string;
  experience: string;
  papersPublished: string;
  pgProjectsGuided: string;
  booksPatents: string;
  professionalMemberships: string;
  consultancy: string;
  patent: string;
  awards: string;
  interactionWithInstitution: string;
  websiteLink: string;
  inCharge: string;
  specialization?: string;
  grants?: string;
  researchLink: string;
  youtubeChannel: string;
  eResources: string;
}

export const csdsfaculty: FacultyProfile[] = [
  {
    slug: 'dr-yogesh-pingle',
    name: 'Dr. Yogesh Pingle',
    photo: '/images/departments/csds/faculty/dr-yogesh-pingle.jpg',
    designation: 'Deputy HOD & Asst. Prof.',
    department: 'Computer Science and Engineering (Data Science)',
    dob: '04/07/1977',
    doj: '06/07/2007',
    qualifications: 'Ph.D. (Computer Engineering, Mumbai University.)\nM.E. (Computers) / 1st class.',
    email: 'yogesh.pingle@vcet.edu.in',
    experience: 'Teaching: 17 years, Industry: 2 years',
    papersPublished: '20',
    pgProjectsGuided: 'M.E. Project - 01 Project Guided at PG Level in 2018.',
    booksPatents: `Total 10 Books Published:
  Internet of Things - 05 Books
  DBMS - 01 Book
  Internet Programming - 02 Books
  Computer Network - 01 Book
  DWM - 01 Book
ISBN Numbers:
978-93-91496-21-0,  978-93-91496-95-1
9789390437436, 978-93-89233-20-9
978-93-89748-80-2,  978-93-5077-090-0
978-93-88200-57-8,  978-93-88200-60-8
978-93-5451-823-2,  978-81-19115-09-9
  11th Book (Year 2003) - Visual Basic Programming, Nirali Prakashan`,
    professionalMemberships: 'LM – ISTE (LM 58653) and LM – CSI (01161406)',
    consultancy: `1. Consultancy for V Enterprises, Nallasopara in 2017 Project – Cold Storage
2. Designed and Developed Website https://avcjr.ac.in/ (Vartak Junior College)
3. Designed and Developed Website https://vcet.edu.in/mms/`,
    patent: `1. Intelligent Wearable Sweat Sensor Based Device For Monitoring and Recommending Personal Physical Fitness Published on 06 Aug 2021
2. Musical Medical Illness Heaking Electronic Device Published on 15 Dec 2023`,
    awards: `Participated in Golden Book of World Record – Musical Instruments as Harmionium Player in June 2016 on occasion of World Music Day (Performed 2 Hours Harmonium Solo in 46 Hours Marathon Performance).
Second Prize in All India Air Instrument National Level Competition in 2004`,
    interactionWithInstitution: 'MoU with L&T, CTEA - Developing L&T Skill Trainers Academy Portal',
    websiteLink: 'Personal Website - http://yogeshpingle.co.in/\nYPP Technologies - https://ypptechnologies.in/',
    inCharge: 'German Language Club\nWebsite Technical Head',
    researchLink: 'ORCID - https://orcid.org/0000-0003-2124-885X\nGoogle Scholar - https://scholar.google.com/scholar?hl=en&as_sdt=0%2C5&q=yogesh+pingle&btnG=&oq=yoge\nScopus - https://www.scopus.com/authid/detail.uri?authorId=57170579400\nWeb of Science - https://www.webofscience.com/wos/author/record/2035051',
    youtubeChannel: 'Internet of Everthing - https://www.youtube.com/watch?v=hHwPuLrAy0k&list=PLEivsV-jI8e9XX6QTy2E7JUGjJBiezv0v\nIoT Mini Project Lab - https://www.youtube.com/watch?v=BUH5Ykkwidk&list=UU_msJm7vwLXVNhHjpeZE_RA&index=13\nDevOps Lab - https://www.youtube.com/watch?v=euMdvSO8dvk&list=UUbULYdSE8KdVEfmDosf287w\nJava Lab - https://www.youtube.com/watch?v=dOfSBcaPSRo&list=UUbgznL7YoVnDpzfDdjaQNFA',
    eResources: 'CP - https://yogeshpingle.home.blog/c-programming/\nIOE - https://yogeshpingle.home.blog/iot/\nML Google Classroom - https://classroom.google.com',
  },
  {
    slug: 'ms-krunali-vartak',
    name: 'Ms. Krunali Vartak',
    photo: '/images/departments/csds/faculty/ms-krunali-vartak.jpg',
    designation: 'Asst. Prof.',
    department: 'Computer Science and Engineering (Data Science)',
    dob: '02/06/1992',
    doj: '23/08/2021',
    qualifications: 'M.E. (Information Technology)',
    email: 'krunali.vartak@vcet.edu.in',
    experience: '10 years',
    papersPublished: '4',
    pgProjectsGuided: '',
    booksPatents: 'Books/IPRs/Patents count: 01 (specific title not provided)',
    professionalMemberships: 'ISTE - Life Membership',
    consultancy: '',
    patent: '',
    awards: '',
    interactionWithInstitution: '',
    websiteLink: '',
    inCharge: '',
    researchLink: '',
    youtubeChannel: '',
    eResources: 'Microprocessor - Google Classroom Link:\nhttps://classroom.google.com/c/NjQ4MDQzMTI0OTQx?cjc=zjgukbw\nGoogle Classroom Code: zjgukbw',
  },
  {
    slug: 'ms-maya-varghese',
    name: 'Ms. Maya Varghese',
    photo: '/images/departments/csds/faculty/ms-maya-varghese.jpg',
    designation: 'Asst. Prof.',
    department: 'Computer Science and Engineering (Data Science)',
    dob: '',
    doj: '04/10/2021',
    qualifications: 'M.E. (Computer Engineering)',
    email: 'maya.varghese@vcet.edu.in',
    experience: '7 years',
    papersPublished: '3',
    pgProjectsGuided: '',
    booksPatents: '',
    professionalMemberships: '',
    consultancy: '',
    patent: '',
    awards: '',
    interactionWithInstitution: '',
    websiteLink: '',
    inCharge: '',
    specialization: 'Graph Mining in Data mining domain',
    grants: 'Grants fetched: Qualified GATE 2012 and received AICTE scholarship for ME',
    researchLink: '',
    youtubeChannel: '',
    eResources: '',
  },
  {
    slug: 'ms-janisa-pereira',
    name: 'Ms. Janisa Pereira',
    photo: '/images/departments/csds/faculty/ms-janisa-pereira.jpg',
    designation: 'Asst. Prof.',
    department: 'Computer Science and Engineering (Data Science)',
    dob: '',
    doj: '20-06-2022',
    qualifications: 'M.E (Computers)',
    email: 'janisa.pereira@vcet.edu.in',
    experience: '4.8 years',
    papersPublished: '6',
    pgProjectsGuided: '',
    booksPatents: '',
    professionalMemberships: '',
    consultancy: '',
    patent: '',
    awards: '',
    interactionWithInstitution: '',
    websiteLink: '',
    inCharge: '',
    specialization: 'Data mining, Web mining',
    researchLink: '',
    youtubeChannel: '',
    eResources: 'Google Classroom Link: (Analysis of Algorithms)\nhttps://classroom.google.com/c/NjUzMzE0NTkxMDE0?cjc=knanj5x\nGoogle Classroom Code: knanj5x',
  },
  {
    slug: 'ms-leena-raut',
    name: 'Ms. Leena Raut',
    photo: '/images/departments/csds/faculty/ms-leena-raut.jpg',
    designation: 'Asst. Prof.',
    department: 'Computer Science and Engineering (Data Science)',
    dob: '',
    doj: '27/06/2023',
    qualifications: 'M.E. (Information Technology)',
    email: 'leena.raut@vcet.edu.in',
    experience: '22 Years',
    papersPublished: '04',
    pgProjectsGuided: '',
    booksPatents: '',
    professionalMemberships: 'LM 104089 – ISTE',
    consultancy: '',
    patent: '',
    awards: '',
    interactionWithInstitution: '',
    websiteLink: '',
    inCharge: '',
    researchLink: '',
    youtubeChannel: '',
    eResources: '1. Google Classroom Link (DL): https://classroom.google.com/c/NjE2MDU2MjAwMjM2\nGoogle Classroom Code: ro5oj4k\n2. Google Classroom Link (SEPM): https://classroom.google.com/c/NjUzNzAzNjgzODYw\nGoogle Classroom Code: mpwtojn\n3. Google Classroom Link (SMA): https://classroom.google.com/c/NjUzMjk4NzEwNjA5\nGoogle Classroom Code: xkwvtkn',
  },
  {
    slug: 'mr-ichhanshu-jaiswal',
    name: 'Mr. Ichhanshu Jaiswal',
    photo: '/images/departments/csds/faculty/mr-ichhanshu-jaiswal.png',
    designation: 'Asst. Prof. (Ph.D. Pursuing)',
    department: 'Computer Science and Engineering (Data Science)',
    dob: '',
    doj: '03/07/2023',
    qualifications: 'Ph.D. in Computer Engineering (Pursuing), M.E. (Information Technology)',
    email: 'ichhanshu.jaiswal@vcet.edu.in',
    experience: '13 Years',
    papersPublished: '13',
    pgProjectsGuided: '',
    booksPatents: '',
    professionalMemberships: '',
    consultancy: '',
    patent: '',
    awards: '',
    interactionWithInstitution: '',
    websiteLink: '',
    inCharge: '',
    specialization: 'Artificial Intelligence, Machine Learning, Deep Learning',
    researchLink: '',
    youtubeChannel: '',
    eResources: '',
  },
  {
    slug: 'ms-shital-cheke',
    name: 'Ms. Shital Cheke',
    photo: '/images/departments/csds/faculty/ms-shital-cheke.jpg',
    designation: 'Asst. Prof.',
    department: 'Computer Science and Engineering (Data Science)',
    dob: '',
    doj: '26 Aug 2024',
    qualifications: 'M.E. (Computer)',
    email: 'shital.cheke@vcet.edu.in',
    experience: '08',
    papersPublished: '03',
    pgProjectsGuided: '',
    booksPatents: '',
    professionalMemberships: '',
    consultancy: '',
    patent: '',
    awards: '',
    interactionWithInstitution: '',
    websiteLink: '',
    inCharge: '',
    specialization: 'Computer Engineering',
    researchLink: '',
    youtubeChannel: '',
    eResources: '',
  },
  {
    slug: 'ms-bhavika-joshi',
    name: 'Ms. Bhavika Joshi',
    photo: '/images/departments/csds/faculty/ms-bhavika-joshi.jpg',
    designation: 'Asst. Prof.',
    department: 'Computer Science and Engineering (Data Science)',
    dob: '',
    doj: '26 Aug 2024',
    qualifications: 'M.E. (Computer Pursuing)',
    email: 'bhavika.joshi@vcet.edu.in',
    experience: '07',
    papersPublished: '01',
    pgProjectsGuided: '',
    booksPatents: '',
    professionalMemberships: '',
    consultancy: '',
    patent: '',
    awards: '',
    interactionWithInstitution: '',
    websiteLink: '',
    inCharge: '',
    specialization: 'Computer Engineering',
    researchLink: '',
    youtubeChannel: '',
    eResources: '',
  },
  {
    slug: 'ms-odilia-gonsalves',
    name: 'Ms. Odilia Gonsalves',
    photo: '/images/departments/csds/faculty/ms-odilia-gonsalves.jpg',
    designation: 'Asst. Prof.',
    department: 'Computer Science and Engineering (Data Science)',
    dob: '',
    doj: '03-07-2023',
    qualifications: 'M.E. ( Information Technology )',
    email: 'odilia.gonsalves@vcet.edu.in',
    experience: '08 Years',
    papersPublished: '06',
    pgProjectsGuided: '',
    booksPatents: '',
    professionalMemberships: '',
    consultancy: '',
    patent: '',
    awards: '',
    interactionWithInstitution: '',
    websiteLink: '',
    inCharge: '',
    specialization: 'Computer Graphics, Operating Systems, Database Management System',
    researchLink: '',
    youtubeChannel: '',
    eResources: '',
  },
];

export const cefaculty: FacultyProfile[] = [
  { slug: 'dr-megha-trivedi', name: 'Dr. Megha Trivedi', photo: '/images/departments/comp/faculty/dr-megha-trivedi.jpg', designation: 'Associate Professor & Head Of Department', department: 'Computer Engineering', dob: '', doj: '', qualifications: '', email: 'megha.trivedi@vcet.edu.in', experience: '', papersPublished: '', pgProjectsGuided: '', booksPatents: '', professionalMemberships: '', consultancy: '', patent: '', awards: '', interactionWithInstitution: '', websiteLink: '', inCharge: '', researchLink: '', youtubeChannel: '', eResources: '' },
  { slug: 'dr-dinesh-patil', name: 'Dr. Dinesh Patil', photo: '/images/departments/comp/faculty/dr-dinesh-patil.jpg', designation: 'Associate Professor', department: 'Computer Engineering', dob: '', doj: '', qualifications: '', email: 'dinesh.patil@vcet.edu.in', experience: '', papersPublished: '', pgProjectsGuided: '', booksPatents: '', professionalMemberships: '', consultancy: '', patent: '', awards: '', interactionWithInstitution: '', websiteLink: '', inCharge: '', researchLink: '', youtubeChannel: '', eResources: '' },
  { slug: 'dr-swapna-borde', name: 'Dr. Swapna Borde', photo: '/images/departments/comp/faculty/dr-swapna-borde.jpg', designation: 'Asst. Prof.', department: 'Computer Engineering', dob: '', doj: '', qualifications: '', email: 'swapna.borde@vcet.edu.in', experience: '', papersPublished: '', pgProjectsGuided: '', booksPatents: '', professionalMemberships: '', consultancy: '', patent: '', awards: '', interactionWithInstitution: '', websiteLink: '', inCharge: '', researchLink: '', youtubeChannel: '', eResources: '' },
  { slug: 'anil-hingmire', name: 'Anil Hingmire', photo: '/images/departments/comp/faculty/anil-hingmire.jpg', designation: 'Asst. Prof. & Deputy HOD', department: 'Computer Engineering', dob: '', doj: '', qualifications: '', email: 'anil.hingmire@vcet.edu.in', experience: '', papersPublished: '', pgProjectsGuided: '', booksPatents: '', professionalMemberships: '', consultancy: '', patent: '', awards: '', interactionWithInstitution: '', websiteLink: '', inCharge: '', researchLink: '', youtubeChannel: '', eResources: '' },
  { slug: 'smita-jawale', name: 'Smita Jawale', photo: '/images/departments/comp/faculty/smita-jawale.jpg', designation: 'Asst. Prof. & Deputy HOD', department: 'Computer Engineering', dob: '', doj: '', qualifications: '', email: 'smita.jawale@vcet.edu.in', experience: '', papersPublished: '', pgProjectsGuided: '', booksPatents: '', professionalMemberships: '', consultancy: '', patent: '', awards: '', interactionWithInstitution: '', websiteLink: '', inCharge: '', researchLink: '', youtubeChannel: '', eResources: '' },
  { slug: 'sunil-katkar', name: 'Sunil Katkar', photo: '/images/departments/comp/faculty/sunil-katkar.jpg', designation: 'Asst. Prof.', department: 'Computer Engineering', dob: '', doj: '', qualifications: '', email: 'sunil.katkar@vcet.edu.in', experience: '', papersPublished: '', pgProjectsGuided: '', booksPatents: '', professionalMemberships: '', consultancy: '', patent: '', awards: '', interactionWithInstitution: '', websiteLink: '', inCharge: '', researchLink: '', youtubeChannel: '', eResources: '' },
  { slug: 'dr-swati-varma', name: 'Dr. Swati Varma', photo: '/images/departments/comp/faculty/dr-swati-varma.jpg', designation: 'Asst. Prof.', department: 'Computer Engineering', dob: '', doj: '', qualifications: '', email: 'swati.varma@vcet.edu.in', experience: '', papersPublished: '', pgProjectsGuided: '', booksPatents: '', professionalMemberships: '', consultancy: '', patent: '', awards: '', interactionWithInstitution: '', websiteLink: '', inCharge: '', researchLink: '', youtubeChannel: '', eResources: '' },
  { slug: 'sanket-patil', name: 'Mr. Sanket Patil', photo: '/images/departments/comp/faculty/sanket-patil.jpg', designation: 'Asst. Prof. (Ph.D. Pursuing)', department: 'Computer Engineering', dob: '', doj: '', qualifications: '', email: 'sanket.patil@vcet.edu.in', experience: '', papersPublished: '', pgProjectsGuided: '', booksPatents: '', professionalMemberships: '', consultancy: '', patent: '', awards: '', interactionWithInstitution: '', websiteLink: '', inCharge: '', researchLink: '', youtubeChannel: '', eResources: '' },
  { slug: 'dr-sneha-mhatre', name: 'Dr. Sneha Mhatre', photo: '/images/departments/comp/faculty/dr-sneha-mhatre.jpg', designation: 'Asst. Prof.', department: 'Computer Engineering', dob: '', doj: '', qualifications: '', email: 'sneha.mhatre@vcet.edu.in', experience: '', papersPublished: '', pgProjectsGuided: '', booksPatents: '', professionalMemberships: '', consultancy: '', patent: '', awards: '', interactionWithInstitution: '', websiteLink: '', inCharge: '', researchLink: '', youtubeChannel: '', eResources: '' },
  { slug: 'vishal-pande', name: 'Mr. Vishal Pande', photo: '/images/departments/comp/faculty/vishal-pande.jpg', designation: 'Asst. Prof.', department: 'Computer Engineering', dob: '', doj: '', qualifications: '', email: 'vishal.pande@vcet.edu.in', experience: '', papersPublished: '', pgProjectsGuided: '', booksPatents: '', professionalMemberships: '', consultancy: '', patent: '', awards: '', interactionWithInstitution: '', websiteLink: '', inCharge: '', researchLink: '', youtubeChannel: '', eResources: '' },
  { slug: 'neha-surti', name: 'Ms. Neha Surti', photo: '/images/departments/comp/faculty/neha-surti.jpg', designation: 'Asst. Prof.', department: 'Computer Engineering', dob: '', doj: '', qualifications: '', email: 'neha.surti@vcet.edu.in', experience: '', papersPublished: '', pgProjectsGuided: '', booksPatents: '', professionalMemberships: '', consultancy: '', patent: '', awards: '', interactionWithInstitution: '', websiteLink: '', inCharge: '', researchLink: '', youtubeChannel: '', eResources: '' },
  { slug: 'brinal-colaco', name: 'Ms. Brinal Colaco', photo: '/images/departments/comp/faculty/brinal-colaco.jpg', designation: 'Asst. Prof. (Ph.D. Pursuing)', department: 'Computer Engineering', dob: '', doj: '', qualifications: '', email: 'brinal.colaco@vcet.edu.in', experience: '', papersPublished: '', pgProjectsGuided: '', booksPatents: '', professionalMemberships: '', consultancy: '', patent: '', awards: '', interactionWithInstitution: '', websiteLink: '', inCharge: '', researchLink: '', youtubeChannel: '', eResources: '' },
  { slug: 'sweety-patil', name: 'Ms. Sweety Patil', photo: '/images/departments/comp/faculty/sweety-patil.jpg', designation: 'Asst. Prof.', department: 'Computer Engineering', dob: '', doj: '', qualifications: '', email: 'sweety.patil@vcet.edu.in', experience: '', papersPublished: '', pgProjectsGuided: '', booksPatents: '', professionalMemberships: '', consultancy: '', patent: '', awards: '', interactionWithInstitution: '', websiteLink: '', inCharge: '', researchLink: '', youtubeChannel: '', eResources: '' },
  { slug: 'soniya-khatu', name: 'Ms. Soniya Khatu', photo: '/images/departments/comp/faculty/soniya-khatu.jpg', designation: 'Asst. Prof.', department: 'Computer Engineering', dob: '', doj: '', qualifications: '', email: 'soniya.khatu@vcet.edu.in', experience: '', papersPublished: '', pgProjectsGuided: '', booksPatents: '', professionalMemberships: '', consultancy: '', patent: '', awards: '', interactionWithInstitution: '', websiteLink: '', inCharge: '', researchLink: '', youtubeChannel: '', eResources: '' },
  { slug: 'bhakti-jadhav', name: 'Ms. Bhakti Jadhav', photo: '/images/departments/comp/faculty/bhakti-jadhav.jpg', designation: 'Asst. Prof.', department: 'Computer Engineering', dob: '', doj: '', qualifications: '', email: 'bhakti.jadhav@vcet.edu.in', experience: '', papersPublished: '', pgProjectsGuided: '', booksPatents: '', professionalMemberships: '', consultancy: '', patent: '', awards: '', interactionWithInstitution: '', websiteLink: '', inCharge: '', researchLink: '', youtubeChannel: '', eResources: '' },
  { slug: 'manali-payghan', name: 'Ms. Manali Payghan', photo: '/images/departments/comp/faculty/manali-payghan.jpg', designation: 'Asst. Prof.', department: 'Computer Engineering', dob: '', doj: '', qualifications: '', email: 'manali.payghan@vcet.edu.in', experience: '', papersPublished: '', pgProjectsGuided: '', booksPatents: '', professionalMemberships: '', consultancy: '', patent: '', awards: '', interactionWithInstitution: '', websiteLink: '', inCharge: '', researchLink: '', youtubeChannel: '', eResources: '' },
  { slug: 'vinal-waghela', name: 'Ms. Vinal Waghela', photo: '/images/departments/comp/faculty/vinal-waghela.jpg', designation: 'Asst. Prof.', department: 'Computer Engineering', dob: '', doj: '', qualifications: '', email: 'vinal.waghela@vcet.edu.in', experience: '', papersPublished: '', pgProjectsGuided: '', booksPatents: '', professionalMemberships: '', consultancy: '', patent: '', awards: '', interactionWithInstitution: '', websiteLink: '', inCharge: '', researchLink: '', youtubeChannel: '', eResources: '' },
  { slug: 'joyce-lemos', name: 'Ms. Joyce Lemos', photo: '/images/departments/comp/faculty/joyce-lemos.jpg', designation: 'Asst. Prof.', department: 'Computer Engineering', dob: '', doj: '', qualifications: '', email: 'joyce.dsouza@vcet.edu.in', experience: '', papersPublished: '', pgProjectsGuided: '', booksPatents: '', professionalMemberships: '', consultancy: '', patent: '', awards: '', interactionWithInstitution: '', websiteLink: '', inCharge: '', researchLink: '', youtubeChannel: '', eResources: '' },
  { slug: 'sridhar-subramanian', name: 'Mr. Sridhar Subramanian', photo: '/images/departments/comp/faculty/sridhar-subramanian.jpg', designation: 'Asst. Prof.', department: 'Computer Engineering', dob: '', doj: '', qualifications: '', email: 'sridhar.s@vcet.edu.in', experience: '', papersPublished: '', pgProjectsGuided: '', booksPatents: '', professionalMemberships: '', consultancy: '', patent: '', awards: '', interactionWithInstitution: '', websiteLink: '', inCharge: '', researchLink: '', youtubeChannel: '', eResources: '' },
  { slug: 'atharva-desai', name: 'Mr. Atharva Desai', photo: '/images/departments/comp/faculty/atharva-desai.jpg', designation: 'Asst. Prof.', department: 'Computer Engineering', dob: '', doj: '', qualifications: '', email: 'atharva.desai@vcet.edu.in', experience: '', papersPublished: '', pgProjectsGuided: '', booksPatents: '', professionalMemberships: '', consultancy: '', patent: '', awards: '', interactionWithInstitution: '', websiteLink: '', inCharge: '', researchLink: '', youtubeChannel: '', eResources: '' },
  { slug: 'awantika-sharma', name: 'Ms. Awantika Sharma', photo: '/images/departments/comp/faculty/awantika-sharma.jpg', designation: 'Asst. Prof.', department: 'Computer Engineering', dob: '', doj: '', qualifications: '', email: 'awantika.sharma@vcet.edu.in', experience: '', papersPublished: '', pgProjectsGuided: '', booksPatents: '', professionalMemberships: '', consultancy: '', patent: '', awards: '', interactionWithInstitution: '', websiteLink: '', inCharge: '', researchLink: '', youtubeChannel: '', eResources: '' },
  { slug: 'shilpa-jaiswal', name: 'Ms. Shilpa Jaiswal', photo: '/images/departments/comp/faculty/shilpa-jaiswal.jpg', designation: 'Asst. Prof.', department: 'Computer Engineering', dob: '', doj: '', qualifications: '', email: 'shilpa.jaiswal@vcet.edu.in', experience: '', papersPublished: '', pgProjectsGuided: '', booksPatents: '', professionalMemberships: '', consultancy: '', patent: '', awards: '', interactionWithInstitution: '', websiteLink: '', inCharge: '', researchLink: '', youtubeChannel: '', eResources: '' },
  { slug: 'vanashree-gaikwad', name: 'Ms. Vanashree Gaikwad', photo: '/images/departments/comp/faculty/vanashree-gaikwad.jpg', designation: 'Asst. Prof.', department: 'Computer Engineering', dob: '', doj: '', qualifications: '', email: 'vanashree.gaikwad@vcet.edu.in', experience: '', papersPublished: '', pgProjectsGuided: '', booksPatents: '', professionalMemberships: '', consultancy: '', patent: '', awards: '', interactionWithInstitution: '', websiteLink: '', inCharge: '', researchLink: '', youtubeChannel: '', eResources: '' },
];
