import type { FacultyData } from './csds/FacultyProfileView';

export const basicFacultyMaps: Record<string, Record<string, FacultyData>> = {
  'mechanical-engineering': {
    'dr-uday-aswalekar': { name: 'Dr. Uday Aswalekar', designation: 'Professor & Head of Department', department: 'Mechanical Engineering', email: 'uday.aswalekar@vcet.edu.in', photo: '/images/departments/mech/faculty/dr-uday-aswalekar.jpg' },
    'dr-ashish-chaudhari': { name: 'Dr. Ashish Chaudhari', designation: 'Associate Professor, Dean R&D', department: 'Mechanical Engineering', email: 'ashish.chaudhari@vcet.edu.in', photo: '/images/departments/mech/faculty/dr-ashish-chaudhari.jpg' },
    'dipak-choudhari': { name: 'Mr. Dipak Choudhari', designation: 'Asst. Prof. (Ph.D. Pursuing)', department: 'Mechanical Engineering', email: 'dipak.choudhari@vcet.edu.in', photo: '/images/departments/mech/faculty/dipak-choudhari.jpg' },
    'vinay-patel': { name: 'Mr. Vinay Patel', designation: 'Asst. Prof. (Ph.D. Pursuing)', department: 'Mechanical Engineering', email: 'vinay.patel@vcet.edu.in', photo: '/images/departments/mech/faculty/vinay-patel.jpg' },
    'dr-swapnil-mane': { name: 'Dr. Swapnil Mane', designation: 'Asst. Prof.', department: 'Mechanical Engineering', email: 'swapnil.mane@vcet.edu.in', photo: '/images/departments/mech/faculty/dr-swapnil-mane.jpg' },
    'vishwas-palve': { name: 'Mr. Vishwas Palve', designation: 'Asst. Prof. (Ph.D. Pursuing)', department: 'Mechanical Engineering', email: 'vishwas.palve@vcet.edu.in', photo: '/images/departments/mech/faculty/vishwas-palve.jpg' },
    'tusharkumar-raut': { name: 'Mr. Tusharkumar Raut', designation: 'Asst. Prof.', department: 'Mechanical Engineering', email: 'tusharkumar.raut@vcet.edu.in', photo: '/images/departments/mech/faculty/tusharkumar-raut.jpg' },
    'priti-vairagi': { name: 'Ms. Priti Vairagi', designation: 'Asst. Prof.', department: 'Mechanical Engineering', email: 'priti.vairagi@vcet.edu.in', photo: '/images/departments/mech/faculty/priti-vairagi.jpg' },
    'kamlesh-bachkar': { name: 'Mr. Kamlesh Bachkar', designation: 'Asst. Prof.', department: 'Mechanical Engineering', email: 'kamlesh.bachkar@vcet.edu.in', photo: '/images/departments/mech/faculty/kamlesh-bachkar.jpg' },
    'mukund-kavekar': { name: 'Mr. Mukund Kavekar', designation: 'Asst. Prof. (Ph.D. Pursuing)', department: 'Mechanical Engineering', email: 'mukund.kavekar@vcet.edu.in', photo: '/images/departments/mech/faculty/mukund-kavekar.jpg' },
    'raahul-krishna': { name: 'Mr. Raahul Krishna', designation: 'Asst. Prof.', department: 'Mechanical Engineering', email: 'raahul.krishna@vcet.edu.in', photo: '/images/departments/mech/faculty/raahul-krishna.jpg' },
    'rishabh-melwanki': { name: 'Mr. Rishabh Melwanki', designation: 'Asst. Prof.', department: 'Mechanical Engineering', email: 'rishabh.melwanki@vcet.edu.in', photo: '/images/departments/mech/faculty/rishabh-melwanki.jpg' },
    'dr-umeshchandra-mane': { name: 'Dr. Umeshchandra Mane', designation: 'Asst. Prof.', department: 'Mechanical Engineering', email: 'umesh.mane@vcet.edu.in', photo: '/images/departments/mech/faculty/dr-umeshchandra-mane.jpg' },
    'avantika-prabhu': { name: 'Ms. Avantika Prabhu', designation: 'Asst. Prof.', department: 'Mechanical Engineering', email: 'avantika.prabhu@vcet.edu.in', photo: '/images/departments/mech/faculty/avantika-prabhu.jpg' },
    'javed-shaikh': { name: 'Mr. Javed Shaikh', designation: 'Asst. Prof.', department: 'Mechanical Engineering', email: 'javed.shaikh@vcet.edu.in', photo: '/images/departments/mech/faculty/javed-shaikh.jpg' },
    'gaurav-bhawde': { name: 'Mr. Gaurav Bhawde', designation: 'Asst. Prof.', department: 'Mechanical Engineering', email: 'gaurav.bhawde@vcet.edu.in', photo: '/images/departments/mech/faculty/gaurav-bhawde.jpg' },
    'akshay-save': { name: 'Mr. Akshay Save', designation: 'Asst. Prof.', department: 'Mechanical Engineering', email: 'akshay.save@vcet.edu.in', photo: '/images/departments/mech/faculty/akshay-save.jpg' },
    'mrunal-kshirsagar': { name: 'Ms. Mrunal Kshirsagar', designation: 'Asst. Prof.', department: 'Mechanical Engineering', email: 'mrunal.gosavi@vcet.edu.in', photo: '/images/departments/mech/faculty/mrunal-kshirsagar.jpg' },
  },
  'electronics-telecommunication': {
    'dr-amrita-ruperee': { name: 'Dr. Amrita Ruperee', designation: 'Professor & Head of Department', department: 'Electronics & Telecommunication', email: 'amrita.ruperee@vcet.edu.in', photo: '/images/departments/extc/faculty/dr-amrita-ruperee.jpg' },
    'dr-vikas-gupta': { name: 'Dr. Vikas Gupta', designation: 'Professor & Dean Academics', department: 'Electronics & Telecommunication', email: 'vikas.gupta@vcet.edu.in', photo: '/images/departments/extc/faculty/dr-vikas-gupta.jpg' },
    'dr-ashish-vanmali': { name: 'Dr. Ashish Vanmali', designation: 'Associate Professor', department: 'Electronics & Telecommunication', email: 'ashish.vanmali@vcet.edu.in', photo: '/images/departments/extc/faculty/dr-ashish-vanmali.jpg' },
    'dr-sunayana-jadhav': { name: 'Dr. Sunayana Jadhav', designation: 'Associate Professor & FY Engg. Co-ordinator', department: 'Electronics & Telecommunication', email: 'sunayana.jadhav@vcet.edu.in', photo: '/images/departments/extc/faculty/dr-sunayana-jadhav.jpg' },
    'shaista-khan': { name: 'Ms. Shaista Khan', designation: 'Asst. Prof. (Ph.D. Pursuing)', department: 'Electronics & Telecommunication', email: 'shaista.khan@vcet.edu.in', photo: '/images/departments/extc/faculty/shaista-khan.jpg' },
    'sandhya-supalkar': { name: 'Ms. Sandhya Supalkar', designation: 'Asst. Prof.', department: 'Electronics & Telecommunication', email: 'sandhya.supalkar@vcet.edu.in', photo: '/images/departments/extc/faculty/sandhya-supalkar.jpg' },
    'ashwini-katkar': { name: 'Ms. Ashwini Katkar', designation: 'Asst. Prof. (Ph.D. Pursuing)', department: 'Electronics & Telecommunication', email: 'ashwini.katkar@vcet.edu.in', photo: '/images/departments/extc/faculty/ashwini-katkar.jpg' },
    'neha-gharat': { name: 'Ms. Neha Gharat', designation: 'Asst. Prof. (Ph.D. Pursuing)', department: 'Electronics & Telecommunication', email: 'neha.gharat@vcet.edu.in', photo: '/images/departments/extc/faculty/neha-gharat.jpg' },
    'trupti-shah': { name: 'Ms. Trupti Shah', designation: 'Asst. Prof.', department: 'Electronics & Telecommunication', email: 'trupti.shah@vcet.edu.in', photo: '/images/departments/extc/faculty/trupti-shah.jpg' },
    'kanchan-sarmalkar': { name: 'Ms. Kanchan Sarmalkar', designation: 'Asst. Prof.', department: 'Electronics & Telecommunication', email: 'kanchan.sarmalkar@vcet.edu.in', photo: '/images/departments/extc/faculty/kanchan-sarmalkar.jpg' },
    'bharati-gondhalekar': { name: 'Ms. Bharati Gondhalekar', designation: 'Asst. Prof.', department: 'Electronics & Telecommunication', email: 'bharati.gondhalekar@vcet.edu.in', photo: '/images/departments/extc/faculty/bharati-gondhalekar.jpg' },
    'sandeep-pawar': { name: 'Mr. Sandeep Pawar', designation: 'Asst. Prof.', department: 'Electronics & Telecommunication', email: 'sandeep.pawar@vcet.edu.in', photo: '/images/departments/extc/faculty/sandeep-pawar.jpg' },
    'sampada-pimpale': { name: 'Ms. Sampada Pimpale', designation: 'Asst. Prof.', department: 'Electronics & Telecommunication', email: 'sampada.pimpale@vcet.edu.in', photo: '/images/departments/extc/faculty/sampada-pimpale.jpg' },
  },
  'civil-engineering': {
    'dr-ajay-radke': { name: 'Dr. Ajay Radke', designation: 'Professor & Head of Department', department: 'Civil Engineering', email: 'ajay.radke@vcet.edu.in', photo: '/images/departments/civil/faculty/dr-ajay-radke.jpg' },
    'dr-archanaa-dongre': { name: 'Dr. Archanaa Dongre', designation: 'Associate Professor', department: 'Civil Engineering', email: 'archanaa.dongre@vcet.edu.in', photo: '/images/departments/civil/faculty/dr-archanaa-dongre.jpg' },
    'dr-jaydeep-chougale': { name: 'Dr. Jaydeep Chougale', designation: 'Asst. Prof.', department: 'Civil Engineering', email: 'jaydeep.chougale@vcet.edu.in', photo: '/images/departments/civil/faculty/dr-jaydeep-chougale.jpg' },
    'puja-ghadi': { name: 'Ms. Puja Ghadi', designation: 'Asst. Prof.', department: 'Civil Engineering', email: 'puja.ghadi@vcet.edu.in', photo: '/images/departments/civil/faculty/puja-ghadi.jpg' },
    'dr-viren-chandanshive': { name: 'Dr. Viren Chandanshive', designation: 'Asst. Prof.', department: 'Civil Engineering', email: 'viren.chandanshive@vcet.edu.in', photo: '/images/departments/civil/faculty/dr-viren-chandanshive.jpg' },
    'vikrant-kothari': { name: 'Mr. Vikrant Kothari', designation: 'Asst. Prof. (Ph.D. Pursuing)', department: 'Civil Engineering', email: 'vikrant.kothari@vcet.edu.in', photo: '/images/departments/civil/faculty/vikrant-kothari.jpg' },
    'arbaz-kazi': { name: 'Mr. Arbaz Kazi', designation: 'Asst. Prof.', department: 'Civil Engineering', email: 'arbaz.kazi@vcet.edu.in', photo: '/images/departments/civil/faculty/arbaz-kazi.jpg' },
    'prakash-panda': { name: 'Mr. Prakash Panda', designation: 'Asst. Prof.', department: 'Civil Engineering', email: 'prakash.panda@vcet.edu.in', photo: '/images/departments/civil/faculty/prakash-panda.jpg' },
    'aishwarya-anil': { name: 'Ms. Aishwarya Anil', designation: 'Asst. Prof.', department: 'Civil Engineering', email: 'aishwarya.anil@vcet.edu.in', photo: '/images/departments/civil/faculty/aishwarya-anil.jpg' },
  },
  'first-year-engineering': {
    'chandrakishori-sonarkar': { name: 'Ms. Chandrakishori Sonarkar', designation: 'Asst. Prof. – M.Sc. (Chemistry)', department: 'First Year Engineering', email: 'c.v.sonarkar@vcet.edu.in', photo: '/images/departments/fe/faculty/chandrakishori-sonarkar.jpg' },
    'beauty-ansari': { name: 'Ms. Beauty Ansari', designation: 'Asst. Prof. – M.Sc. (Chemistry) SET', department: 'First Year Engineering', email: 'beauty.ansari@vcet.edu.in', photo: '/images/departments/fe/faculty/beauty-ansari.jpg' },
    'dr-rhushirajeshwari-naik': { name: 'Dr. Rhushirajeshwari Naik', designation: 'Asst. Prof. – Ph.D. (Chemistry)', department: 'First Year Engineering', email: 'rhushirajeshwari.naik@vcet.edu.in', photo: '/images/departments/fe/faculty/dr-rhushirajeshwari-naik.jpg' },
    'dipa-patel': { name: 'Ms. Dipa Patel', designation: 'Asst. Prof. – M.Sc. (Chemistry), Ph.D. Pursuing', department: 'First Year Engineering', email: 'dipa.patel@vcet.edu.in', photo: '/images/departments/fe/faculty/dipa-patel.jpg' },
    'vaishnavi-gurav': { name: 'Ms. Vaishnavi Gurav', designation: 'Asst. Prof. – M.Sc. (Physics)', department: 'First Year Engineering', email: 'vaishnavi.gurav@vcet.edu.in', photo: '/images/departments/fe/faculty/vaishnavi-gurav.jpg' },
    'vikas-bhagat': { name: 'Mr. Vikas Bhagat', designation: 'Asst. Prof. – M.Sc. (Physics)', department: 'First Year Engineering', email: 'vikas.bhagat@vcet.edu.in', photo: '/images/departments/fe/faculty/vikas-bhagat.jpg' },
    'neha-shah': { name: 'Ms. Neha Shah', designation: 'Asst. Prof. – M.Sc. B.Ed (Physics)', department: 'First Year Engineering', email: 'neha.shah@vcet.edu.in', photo: '/images/departments/fe/faculty/neha-shah.jpg' },
    'dr-kavita-churi': { name: 'Dr. Kavita Churi', designation: 'Asst. Prof. – Ph.D. (Physics)', department: 'First Year Engineering', email: 'kavita.churi@vcet.edu.in', photo: '/images/departments/fe/faculty/dr-kavita-churi.jpg' },
    'ankita-mane': { name: 'Ms. Ankita Mane', designation: 'Asst. Prof. – M.Sc. (Maths), Ph.D. Pursuing', department: 'First Year Engineering', email: 'ankita.mane@vcet.edu.in', photo: '/images/departments/fe/faculty/ankita-mane.jpg' },
    'praiza-gonsalves': { name: 'Ms. Praiza Gonsalves', designation: 'Asst. Prof. – M.Sc. (Maths)', department: 'First Year Engineering', email: 'praiza.gonsalves@vcet.edu.in', photo: '/images/departments/fe/faculty/praiza-gonsalves.jpg' },
    'mayur-gohil': { name: 'Mr. Mayur Gohil', designation: 'Asst. Prof. – M.A. (Maths) SET', department: 'First Year Engineering', email: 'mayur.gohil@vcet.edu.in', photo: '/images/departments/fe/faculty/mayur-gohil.jpg' },
    'ganesh-tilave': { name: 'Mr. Ganesh Tilave', designation: 'Asst. Prof. – M.Sc. (Maths) SET', department: 'First Year Engineering', email: 'ganesh.tilave@vcet.edu.in', photo: '/images/departments/fe/faculty/ganesh-tilave.jpg' },
    'anahita-pereira': { name: 'Ms. Anahita Pereira', designation: 'Asst. Prof. – M.Sc. (Maths), Ph.D. Pursuing', department: 'First Year Engineering', email: 'anahita.pereira@vcet.edu.in', photo: '/images/departments/fe/faculty/anahita-pereira.jpg' },
    'deepika-panchal': { name: 'Ms. Deepika Panchal', designation: 'Asst. Prof. – M.Sc. (Maths)', department: 'First Year Engineering', email: 'deepika.panchal@vcet.edu.in', photo: '/images/departments/fe/faculty/deepika-panchal.jpg' },
    'sachin-gondke': { name: 'Mr. Sachin Gondke', designation: 'Asst. Prof. – M.Sc. (Maths) NET, SET', department: 'First Year Engineering', email: 'sachin.gondke@vcet.edu.in', photo: '/images/departments/fe/faculty/sachin-gondke.jpg' },
    'dr-pradip-gulbhile': { name: 'Dr. Pradip Gulbhile', designation: 'Asst. Prof. – Ph.D. (English)', department: 'First Year Engineering', email: 'pradip.gulbhile@vcet.edu.in', photo: '/images/departments/fe/faculty/dr-pradip-gulbhile.jpg' },
    'kamini-more': { name: 'Ms. Kamini More', designation: 'Asst. Prof. – M.A. (English) M.Phil', department: 'First Year Engineering', email: 'kamini.more@vcet.edu.in', photo: '/images/departments/fe/faculty/kamini-more.jpg' },
    'gloria-collaco': { name: 'Ms. Gloria Collaco', designation: 'Asst. Prof. – M.A. (English) SET', department: 'First Year Engineering', email: 'gloria.collaco@vcet.edu.in', photo: '/images/departments/fe/faculty/gloria-collaco.jpg' },
    'dr-tanya-dsouza': { name: "Dr. Tanya D'souza", designation: 'Asst. Prof. – Ph.D. (English) NET, SET', department: 'First Year Engineering', email: 'tanya.dsouza@vcet.edu.in', photo: '/images/departments/fe/faculty/dr-tanya-dsouza.jpg' },
    'dr-aashi-cynth': { name: 'Dr. Aashi Cynth', designation: 'Asst. Prof. – Ph.D. (English)', department: 'First Year Engineering', email: 'aashi.cynth@vcet.edu.in', photo: '/images/departments/fe/faculty/dr-aashi-cynth.jpg' },
    'jenisa-dsilva': { name: "Ms. Jenisa D'silva", designation: 'Asst. Prof. – M.A. (English)', department: 'First Year Engineering', email: 'jenisa.dsilva@vcet.edu.in', photo: '/images/departments/fe/faculty/jenisa-dsilva.jpg' },
    'shraddha-gosavi': { name: 'Ms. Shraddha Gosavi', designation: 'Asst. Prof. – M.E. (EXTC)', department: 'First Year Engineering', email: 'shraddha.gosavi@vcet.edu.in', photo: '/images/departments/fe/faculty/shraddha-gosavi.jpg' },
    'tarranum-khan': { name: 'Ms. Tarranum Khan', designation: 'Asst. Prof. – M.Tech (Civil)', department: 'First Year Engineering', email: 'tarranum.khan@vcet.edu.in', photo: '/images/departments/fe/faculty/tarranum-khan.jpg' },
    'prachee-shah': { name: 'Ms. Prachee Shah', designation: 'Asst. Prof. – M.E. (Electronics)', department: 'First Year Engineering', email: 'prachee.shah@vcet.edu.in', photo: '/images/departments/fe/faculty/prachee-shah.jpg' },
    'rojal-rodrigues': { name: 'Ms. Rojal Rodrigues', designation: 'Asst. Prof. – M.E. (EXTC)', department: 'First Year Engineering', email: 'rojal.rodrigues@vcet.edu.in', photo: '/images/departments/fe/faculty/rojal-rodrigues.jpg' },
  },
};
